@apidoc=http://localhost:8080/apidoc
# @apidoc=http://api.xlongwei.com/apidoc
# @apidoc=https://api.xlongwei.com/apidoc
### html
{{apidoc}}/pass/swagger2html.htm?jsonUrl={{apidoc}}/pass/knife4j/swagger.htm?docId=1
### mock
{{apidoc}}/pass/apidoc/demo.htm?doc=1&mock=true
### swagger mock
{{apidoc}}/pass/knife4j/swagger.htm?docId=1&mock=true
### mock pager
{{apidoc}}/mock/user/simple/pager.htm?pageNumber=1&pageSize=10
### get pager
{{apidoc}}/demo/user/simple/pager.htm?pageNumber=1&pageSize=10
### tomcat/bin/catalina.sh
-Xms74m
-Xmx74m
-Xmn10m
-Xss228k
-server
-XX:SurvivorRatio=8
-Djava.awt.headless=true
-Djava.compiler=none
-Duser.timezone=GMT+8
-Dcom.mysql.cj.disableAbandonedConnectionCleanup=true